# Nhóm các máy thuộc VLAN 10 (Sinh viên)
[vlan10]
client_1 ansible_host=192.168.10.100

# Nhóm các máy thuộc VLAN 20 (Giảng viên)
[vlan20]
client_2 ansible_host=192.168.20.100 ansible_user=client-2

# Nhóm tổng hợp tất cả các máy Client
[clients:children]
vlan10
vlan20

# Cấu hình chung cho tất cả các máy trong inventory
[all:vars]
ansible_user=nt132-client
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'