name: CI/CD NetDevOps Nhóm 4

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Check Python Syntax
        run: |
          python3 -m py_compile python/test_ssh_router.py

      - name: Check Ansible Syntax
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          ansible-playbook ansible/deploy_web.yml --syntax-check